###########################
#                         #
#     InvisibleFrames     #
#                         #
###########################

# Количество частиц при смене видимости рамки
countParticles: 10

# Радиус от рамки, в котором будет слышен звук смены видимости рамки
radius: 5.0

# С какой громкостью будет проигрываться звук смены видимости рамки
volume: 0.2